### ISSUE TITLE
The old status bar doesn’t update the icon frequently

### ISSUE THREAD

**Issue by zgibberish** [Traurige/BatteryBuddy#3]
**Describe the bug:**
- When I respring the battery looks like the default one until i toggle on/off low power mode.
- When I  plug/unplug the charger the lightning symbol next to the battery icon doesnt update until i toggle low power mode.

**System information:**
- Device: iPhone 6s
- iOS version: 14.4.2
- Jailbreak: Odysseyra1n

**Comment by Traurige** [comment]
I just tried it myself and I'm not experiencing any issues. Perhaps it's some tweak conflict on your side?

**Comment by xXbaodeptraiXx** [comment]
> I just tried it myself and I'm not experiencing any issues. Perhaps it's some tweak conflict on your side?

Might be, but the only battery related tweak i have installed is LowLock, which i tried uninstalling but that didnt fix the issue. I'm currently trying to disable all the tweaks to see which one causes the conflict

**Comment by xXbaodeptraiXx** [comment]
Update: i just found out that the problem only occurs when low power mode is on, when low power mode is turned off the battery icon updates normally

**Comment by xXbaodeptraiXx** [comment]
another update: Ive tried disabling every tweak and enabling them one by one, i am almost certain that this is a problem with Battery Buddy, when i disable Battery Buddy, the battery icon updates normally even when low power mode is on.

**Comment by Traurige** [comment]
It might be an issue with the old status bar. I don't have any jailbroken home button device at the moment, though.

**Comment by xXbaodeptraiXx** [comment]
> It might be an issue with the old status bar. I don't have any jailbroken home button device at the moment, though.

no problem at all, ill try looking through the source code, i dont know C though but its worth a try

**Comment by Traurige** [comment]
Yeah, I figured the old status bar acts differently than the modern one. Not sure if and when I can fix it.

**Comment by Traurige** [comment]
I take decisions as time moved on. I will not work on this, but if anyone else wants to, sure.

**Comment by zgibberish** [comment]
> I take decisions as time moves on. I will not work on this, but if anyone else wants to, sure.

yeah that's fine, can you add a note about compatibility in README.md so people know about this issue?
