### ISSUE TITLE
palera1n 15.7

### ISSUE THREAD

**Issue by ThomasXDA** [Traurige/BatteryBuddy#7]
Sorry for my bad english, frist. Hi!
I love this cute tweak and use it from ios 13... so after jailbreak 15.7.1 I try it. its work perfectly ^_^ 
BUT i lost my respring button.
After install BatteryBuddy when my ios needed respring like set setting on another tweaks or... my phone is reboot //  freeze on respring & reboot automatic :(  //
I want you to if you can solve this problem in your free time.
thanks
**System information:**
- iOS version: 15.7.1
- Device: ip 6s
- Jailbreak: palera1n

**Comment by Traurige** [comment]
I don't quite understand what you're trying to say. I need more info and if applicable a crash log. Does it "reboot" after installing or because of the respring button in the preferences?

**Comment by ThomasXDA** [comment]
Thank you for replying
Okay. I installed this tweak as .deb file
 After that, when I want to respring my phone, for example change color on accent, the phone gets stuck in respring mode and reboots itself after a few minutes.

**Comment by ThomasXDA** [comment]
The problem is solved only when I remove the battery buddy :(((

**Comment by Traurige** [comment]
Perhaps something crashes during the respring. If yes, then I'll need a crash log. I also need to know if that's a BatteryBuddy or palera1n problem. I don't have a palera1n device so I'll need you to find out. You could ask fellow palera1n users.

**Comment by ThomasXDA** [comment]
Yes. Now that I think, maybe the problem is the palera1n. its beta and not work with many tweak...
Anyway. I will be happy if I can help in solving this problem. How to prepare crash log?

**Comment by Traurige** [comment]
Cr4shed generates crash logs. If it happens to get you one share it via pastebin, please.

**Comment by Traurige** [comment]
I don't and can't have a palera1n device so I'm marking this as 'won't fix'. I will also close it due to inactivity caused by missing responses.
