### ISSUE TITLE
Not showing in apps

### ISSUE THREAD

**Issue by Felting** [Traurige/BatteryBuddy#8]
**Describe the bug:**
The battery buddy does not show in apps
**Steps to reproduce the behavior:**
Open app
**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version: 16.1.2
- Device: iPhone 8
- Jailbreak: palera1n

**Comment by Traurige** [comment]
You can likely fix this by using the iPhone X / Modern Status Bar. The old one works differently to the modern one.

**Comment by Felting** [comment]
> You can likely fix this by using the iPhone X / Modern Status Bar. The old one works differently to the modern one.

What tweak would be used to do this on ios 16?

**Comment by Traurige** [comment]
You’ll have to ask somewhere else, I don’t know.
